<?php

if (WP_DEBUG == true) {

  /* Ativar para Fazer Debug aos Campos */
  add_filter('acf/settings/remove_wp_meta_box', '__return_false');

}

if( function_exists('acf_add_local_field_group') && (get_option('nau_environment') == "prod")):

// copiar de "Custom-Fields, Tools, Generate PHP" e colocar aqui.

acf_add_local_field_group(array(
	'key' => 'group_5e8762b7eab59',
	'title' => 'Curso',
	'fields' => array(
		array(
			'key' => 'field_5e99d36dddd30',
			'label' => 'Sincronização',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e876c42c4ff3',
			'label' => 'Entidade Promotora do Curso',
			'name' => 'nau-organization',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => array(
				0 => 'category:entidade',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_5e876be191d89',
			'label' => 'Course ID PROD',
			'name' => 'course-id-prod',
			'type' => 'text',
			'instructions' => 'CourseID que referencia o curso em PROD',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8762bdae30f',
			'label' => 'Course ID',
			'name' => 'nau_lms_course_id',
			'type' => 'text',
			'instructions' => 'Course ID em Stage',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e99d391ddd31',
			'label' => 'Atualizar Synopse do Curso',
			'name' => 'update-overview',
			'type' => 'true_false',
			'instructions' => 'Se verdadeiro, a página é atualizada com os dados provindos do STUDIO.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ea177c43c919',
			'label' => 'Bloquear (todas) Atualizações Automaticas',
			'name' => 'block-auto-updates',
			'type' => 'true_false',
			'instructions' => 'Se verdadeiro, a página nunca é atualizada, nem conteúdo, nem metadados!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f21f52f561f3',
			'label' => 'Confluence URL',
			'name' => 'confluence_url',
			'type' => 'url',
			'instructions' => 'Endereço Confluence',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e934607a2ddc',
			'label' => 'Visualização',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e8a8120b3b32',
			'label' => 'Cor de Cartão',
			'name' => 'card-color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#2010AA',
		),
		array(
			'key' => 'field_5eb5f68727bb9',
			'label' => 'Largura do Cartão',
			'name' => 'card_width',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'single' => 'Uma unidade',
				'double' => 'Duas unidades',
			),
			'default_value' => array(
				0 => 'single',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5eb62092cd5b1',
			'label' => 'Disposição da Imagem no Cartão',
			'name' => 'image_fit',
			'type' => 'select',
			'instructions' => 'Expande - ajusta o tamanho da imagem para ocupar todo o espaço referente à image, pode tornar parte da imagem invisivel
Contém - ajusta o tamanho da imagem para o tamanho máximo, apresentando toda a imagem',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'cover' => 'Expande',
				'contain' => 'Contém',
			),
			'default_value' => array(
				0 => 'contain',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ea0fb75a7af8',
			'label' => 'Imagem',
			'name' => 'nau_lms_course_media_image_raw',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8a8768714eb',
			'label' => 'Diretiva de Sustentabilidade',
			'name' => 'un-sustentability',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Nenhum',
				1 => 'Erradicar a pobreza',
				2 => 'Erradicar a fome',
				3 => 'Saúde de qualidade',
				4 => 'Educação de qualidade',
				5 => 'Igualdade de género',
				6 => 'Água potável e saneamento',
				7 => 'Energias renováveis e acessível',
				8 => 'Trabalho digno e crescimento económico',
				9 => 'Indústria, inovação e infraestruturas',
				10 => 'Reduzir as desigualdades',
				11 => 'Cidades e comunidades sustentáveis',
				12 => 'Produção e consumo responsáveis',
				13 => 'Acção climática',
				14 => 'Proteger a vida marinha',
				15 => 'Proteger a vida terrestre',
				16 => 'Paz, justiça e instituições eficazes',
				17 => 'Parcerias e meios de implementação dos objetivos',
			),
			'default_value' => array(
				0 => 0,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e8a8cca91777',
			'label' => 'Youtube',
			'name' => 'youtube',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ea8927037222',
			'label' => 'Tagline',
			'name' => 'tagline',
			'type' => 'text',
			'instructions' => 'Linha de texto adicional que acompanha o título.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8762d9ae310',
			'label' => 'Meta',
			'name' => 'meta',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5eaeead29d989',
			'label' => 'Tipo de Certificado',
			'name' => 'certificate_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'hidden' => 'escondido',
				'none' => 'Nenhum',
				'bronze' => 'Bronze',
				'silver' => 'Prata',
				'gold' => 'Ouro',
			),
			'default_value' => array(
				0 => 'hidden',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e9344dc2f5b7',
			'label' => 'Informações',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e99d5bccb4d4',
			'label' => 'Inicio',
			'name' => 'nau_lms_course_start',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'Y-m-d H:i:s',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5e99d5f8cb4d5',
			'label' => 'Fim',
			'name' => 'nau_lms_course_end',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'Y-m-d H:i:s',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5e99d60fcb4d6',
			'label' => 'Esforço',
			'name' => 'nau_course_extra_about_effort',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8a8c594697f',
			'label' => 'Custo',
			'name' => 'cost',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ea88f0074213',
			'label' => 'Visibilidade',
			'name' => 'nau_lms_course_catalog_visibility',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'a página é privada, não é apresentada em nenhuma situação',
				'about' => 'a página é apresentada de forma independente, mas não nas listagens',
				'both' => 'a página é apresentada de forma independente e surge nas listagens',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ea88f3b74214',
			'label' => 'Pace Mode',
			'name' => 'nau_lms_course_self_paced',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Instructor Paced',
				1 => 'Self Paced',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ea88f7674215',
			'label' => 'Apenas por convite',
			'name' => 'nau_lms_course_invitation_only',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Não',
				1 => 'Sim',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ea88fa974216',
			'label' => 'Apenas para Staff',
			'name' => 'nau_lms_course_visible_to_staff_only',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Não',
				1 => 'Sim',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e99d673398f5',
			'label' => 'Meta',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e93454b2f5b9',
			'label' => 'Certificados',
			'name' => 'nau_lms_course_certificates',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5e9344f02f5b8',
			'label' => 'Inscritos',
			'name' => 'nau_lms_course_enrollments',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5e8a8ec0c2f86',
			'label' => 'Estrelas',
			'name' => 'stars',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 1,
			'max' => 5,
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:curso',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Campos Relacionados com os Cursos',
));

acf_add_local_field_group(array(
	'key' => 'group_5e875bc5b7240',
	'title' => 'Entidade',
	'fields' => array(
		array(
			'key' => 'field_5e875ea6a4e03',
			'label' => 'NAU-ID',
			'name' => 'nau-id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8f51cb36489',
			'label' => 'Entity SLUG',
			'name' => 'slug',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e875e82a4e02',
			'label' => 'SIGLA',
			'name' => 'sigla',
			'type' => 'text',
			'instructions' => 'Sigla da Entidade',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 32,
		),
		array(
			'key' => 'field_5e87603e8e157',
			'label' => 'Logótipo',
			'name' => 'logo',
			'type' => 'url',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e875f7ef7f30',
			'label' => 'WebSite',
			'name' => 'website',
			'type' => 'url',
			'instructions' => 'Website da Entidade',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e875edea4e04',
			'label' => 'Logótipo Quadrado',
			'name' => 'square-logo',
			'type' => 'image',
			'instructions' => 'Link para imagem. Se existir tem preferência sobre o campo "logo"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5e875f98f7f31',
			'label' => 'YouTube',
			'name' => 'youtube',
			'type' => 'text',
			'instructions' => 'Código do vídeo youtube a apresentar na página.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 32,
		),
		array(
			'key' => 'field_5e875be6355f6',
			'label' => 'Meta',
			'name' => 'meta',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5e8760548e158',
			'label' => 'Morada',
			'name' => 'address',
			'type' => 'textarea',
			'instructions' => 'Morada completa da Entidade',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5f21f4e270372',
			'label' => 'Confluence URL',
			'name' => 'confluence_url',
			'type' => 'url',
			'instructions' => 'Endereço da entidade no Confluence',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:entidade',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Campos relacionados com entidades',
));

acf_add_local_field_group(array(
	'key' => 'group_5e8a25f07dfcd',
	'title' => 'Home Page',
	'fields' => array(
		array(
			'key' => 'field_5e89900e536b1',
			'label' => 'Componentes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e8990b3536b2',
			'label' => 'Top Slider',
			'name' => 'homepage-top-slider',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Desligado',
				1 => 'Ligado',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e8a0a2960b17',
			'label' => 'Highlight Courses',
			'name' => 'homepage-highlight-courses',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Desligado',
				1 => 'Ligado',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e8a0a4b60b18',
			'label' => 'Destaque de Cursos Ativos',
			'name' => 'homepage-running-courses',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Desligado',
				1 => 'Ligado',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e8a0a7d60b19',
			'label' => 'Faixa para Entidades Fundadoras',
			'name' => 'homepage-founder-entities',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Desligado',
				1 => 'Ligado',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5e8a0c50168ab',
			'label' => 'Slider',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e8990b3536b2',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e8a0d36642ad',
			'label' => 'Posição 1',
			'name' => 'homepage-slider-1',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a0d8803b88',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a0dbb03b89',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a0ef3fc0fe',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a0f13fc0ff',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a0f6f6ca2f',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a0fac6ca30',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a15a01e3ef',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a15c01e3f0',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a241fddba1',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a2437ddba2',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a591af0dd4',
					'label' => 'Cor de Fundo',
					'name' => 'back-color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
				),
				array(
					'key' => 'field_5e97cc96b0a11',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a0d8803b88',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a25c7d1ae2',
			'label' => 'Posição 2',
			'name' => 'homepage-slider-2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a25c7d1ae3',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25c7d1ae4',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
					'preview_size' => 'medium',
					'library' => '',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a25c7d1ae5',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25c7d1ae6',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25c7d1ae7',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25c7d1ae8',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25c7d1ae9',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25c7d1aea',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25c7d1aeb',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a25c7d1aec',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e99d6d6ab569',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25c7d1ae3',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a25ccd1aed',
			'label' => 'Posição 3',
			'name' => 'homepage-slider-3',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a25ccd1aee',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25ccd1aef',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
					'preview_size' => 'medium',
					'library' => '',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a25ccd1af0',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25ccd1af1',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25ccd1af2',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25ccd1af3',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25ccd1af4',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25ccd1af5',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25ccd1af6',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a25ccd1af7',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e99d741ab56a',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25ccd1aee',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a25d0d1af8',
			'label' => 'Posição 4',
			'name' => 'homepage-slider-4',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a25d0d1af9',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25d0d1afa',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a25d0d1afb',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25d0d1afc',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25d0d1afd',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25d0d1afe',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25d0d1aff',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25d0d1b00',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25d0d1b01',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a25d0d1b02',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5eaabc4df4fe0',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25d0d1af9',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a25dae04cd',
			'label' => 'Posição 5',
			'name' => 'homepage-slider-5',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a25dae04ce',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25dae04cf',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
					'preview_size' => 'medium',
					'library' => '',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a25dae04d0',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25dae04d1',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25dae04d2',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25dae04d3',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25dae04d4',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25dae04d5',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25dae04d6',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a25dae04d7',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5eaabccbf4fe1',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25dae04ce',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a25e1e04d8',
			'label' => 'Posição 6',
			'name' => 'homepage-slider-6',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a25e1e04d9',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25e1e04da',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
					'preview_size' => 'medium',
					'library' => '',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a25e1e04db',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25e1e04dc',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25e1e04dd',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25e1e04de',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25e1e04df',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25e1e04e0',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25e1e04e1',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a25e1e04e2',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5eaabd0bf4fe2',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e1e04d9',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a25e6e04e3',
			'label' => 'Posição 7',
			'name' => 'homepage-slider-7',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a25e6e04e4',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25e6e04e5',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
					'preview_size' => 'medium',
					'library' => '',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a25e6e04e6',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25e6e04e7',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a25e6e04e8',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a25e6e04e9',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25e6e04ea',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25e6e04eb',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a25e6e04ec',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a25e6e04ed',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5eaabd17f4fe3',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a25e6e04e4',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a296af307a',
			'label' => 'Posição 8',
			'name' => 'homepage-slider-8',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5e8a296af307b',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'off' => 'Desligado',
						'link' => 'Destaque',
						'video' => 'Video',
						'search' => 'Pesquisa',
						'news' => 'Noticia',
						'course' => 'Curso',
						'entity' => 'Entidade',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a296af307c',
					'label' => 'Imagem',
					'name' => 'backimage',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'link',
							),
						),
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'search',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => 1000,
					'min_height' => 450,
					'min_size' => '',
					'max_width' => 2000,
					'max_height' => 600,
					'max_size' => '',
					'mime_types' => 'png,jpg',
				),
				array(
					'key' => 'field_5e8a296af307d',
					'label' => 'Texto Primário',
					'name' => 'primary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a296af307e',
					'label' => 'Texto Secundário',
					'name' => 'secondary-line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '!=',
								'value' => 'off',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e8a296af307f',
					'label' => 'Link Externo',
					'name' => 'link-external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e8a296af3080',
					'label' => 'Link Interno Curso',
					'name' => 'link-internal-course',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'course',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:curso',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a296bf3081',
					'label' => 'Link Interno Noticia',
					'name' => 'link-internal-news',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'news',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => array(
						0 => 'category:noticia',
					),
					'allow_null' => 0,
					'allow_archives' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a296bf3082',
					'label' => 'Link Interno Entidade',
					'name' => 'link-internal-entity',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'entity',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => array(
						0 => 'category:entidade',
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5e8a296bf3083',
					'label' => 'Opacidade',
					'name' => 'opacity',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '0.9',
					'min' => '',
					'max' => 1,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e8a296bf3084',
					'label' => 'Tonalidade',
					'name' => 'hue',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 360,
					'step' => 5,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5eaabd1cf4fe4',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e8a296af307b',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
			'key' => 'field_5e8a80389d0f8',
			'label' => 'Links da Página',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e8a804b9d0f9',
			'label' => 'Todos os cursos',
			'name' => 'all-courses',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e8a5bc854436',
	'title' => 'Noticia',
	'fields' => array(
		array(
			'key' => 'field_5e8a5bd67a1f8',
			'label' => 'Sub-titulo',
			'name' => 'tagline',
			'type' => 'text',
			'instructions' => 'Preencher com sub-titulo da notícia.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:noticia',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e87623333424',
	'title' => 'Página',
	'fields' => array(
		array(
			'key' => 'field_5e8a0b7d5914e',
			'label' => 'Visualização',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e9b108ebf441',
			'label' => 'Cabeçalho',
			'name' => 'header',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'null' => 'sem banner',
				'nau' => 'NAU Banner',
				'nau-black' => 'NAU Black Banner',
				'un' => 'Nações Unidas',
			),
			'default_value' => array(
				0 => 'nau',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e87625697bbd',
			'label' => 'Cor',
			'name' => 'color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5e8a61a08035f',
			'label' => 'Opacidade',
			'name' => 'opacity',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '0.9',
			'min' => '0.4',
			'max' => 1,
			'step' => '0.05',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5eaab657bb125',
			'label' => 'Grayscale',
			'name' => 'grayscale',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'min' => '',
			'max' => 1,
			'step' => '0.1',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5e8a61c580360',
			'label' => 'Tonalidade',
			'name' => 'hue',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'min' => 0,
			'max' => 360,
			'step' => 5,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5e97aaac629a1',
			'label' => 'Imagem',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5e999d43b2286',
			'label' => 'Pixels',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e999d52b2287',
			'label' => 'Tracking Code',
			'name' => 'pixel-track-code',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '!=',
				'value' => 'home.php',
			),
		),
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:noticia',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Campos associados a todas as páginas do Tema',
));

acf_add_local_field_group(array(
	'key' => 'group_5e8d97bd25d90',
	'title' => 'Redirector',
	'fields' => array(
		array(
			'key' => 'field_5e8d97c5272a2',
			'label' => 'Destino',
			'name' => 'target',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'redirector.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;